### ISSUE TITLE
Charm does not add baremetal to ml2_conf.ini file

### ISSUE THREAD

**Issue by QthePirate** [gabriel-samfira/charm-neutron-api-plugin-ironic#1]
After relation of neutron-api to neutron-api-plugin-ironic, the ml2_conf.ini file should be updated to use the baremetal driver.

Whats SUPPOSED to happen:
mechanism_drivers = openvswitch,hyperv,l2population,baremetal

What happens:
mechanism_drivers = openvswitch,hyperv,l2population     (nothing)

As per: https://docs.openstack.org/ironic/ussuri/install/configure-networking.html

**Comment by gabriel-samfira** [comment]
What bundle did you use? I can't reproduce this with the test bundles available here:

https://github.com/gabriel-samfira/charm-ironic-api/blob/master/src/tests/bundles/bionic-ussuri.yaml

Also, these charms are under active development. Not all are yet available in the charm store in their final form. Your results may vary. I suggest you wait until they are officially released.

**Comment by QthePirate** [comment]
@gabriel-samfira 

I used the one available in the charm store by you:

 cs:~gabriel-samfira/neutron-api-plugin-ironic-1

On an already existing openstack infrastructure

I'm not concerned whether its are fully completed or not, i'm just attempting to help find the bugs. 

It applies the ironic neutron conf file propery in the ml2 folder, just doesnt add it to ml2_conf.ini
